= Cordova Showcase Application Template

image:https://img.shields.io/badge/Android-Compatible-green.svg[]
image:https://img.shields.io/badge/iOS-Compatible-green.svg[]
image:https://img.shields.io/badge/Ionic%20Version-3-green.svg[]
image:https://img.shields.io/badge/Angular%20Version-4-green.svg[]
image:https://badges.frapsoft.com/typescript/code/typescript.svg?v=101[]
image:https://circleci.com/gh/aerogear/cordova-showcase-template.svg?&style=shield[link=https://circleci.com/gh/aerogear/cordova-showcase-template]

A template application to showcase features from link:https://github.com/aerogear/aerogear-js-sdk[Aerogear Js SDK].

As this application showcases features from link:https://github.com/aerogear/aerogear-js-sdk[Aerogear Js SDK] ensure you checkout the desired git tag for whatever SDK version you intend to run. Check link:https://www.npmjs.com/org/aerogear[NPM] for associated versions and releases.
== Build Instructions

=== Running the App
This application can be run as a showcase using a published version of the AeroGear Js SDK, or as a development aid to working on the SDK.

==== Run Showcase
The `master` branch will always track to the latest release of the SDK.

To build the showcase app, run:
```
npm install
npm run ionic:build
```
You can choose to run the application in either an emulator or a browser.
```
npm run ionic:serve // to run a browser

npm run ionic:android // to run in an android emulator

npm run ionic:ios // to run in an ios emulator
```

Note: If after running the application for iOS you get the following error: 
```
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

run the following command from the root of the directory:
```
cd platforms/ios && pod install
```

and then re build the application.

==== Development and Contributing
Looking to use the showcase for development purposes with the SDK please take some time to read the link:./CONTRIBUTING.md[General Contributing Guide]
